<center> <h1> Application Programming Interface </h> </center> 
<center> <h2> Classroom Activity 2 </h> </center> 
<center> <h3> Crime API </h> </center>

The Hoyodecrimen REST API (https://hoyodecrimen.com/api/) allows to query crime data about Mexico City. 

Complete the following tasks:

* Obtain a **list** of all crime types in the Database.
* Obtain all quadrants in the Database and store them into a table with the following columns:
    * cuadrante
    * cve_mun
    * municipio
    * sector
* Create a function to obtain all the crimes within a certain distance given the geographic coordinates of a point (lat/lon). Create a table locating the crimes near to the Zocalo (19.433735, -99.133334):
    * crime
    * date
    * hour
    * lat
    * lon
* Obtain the top ranked quadrants the highest crime counts in 2016, 2017, 2018. Create a unique table including:
    * year
    * crime
    * quadrant
    * difference
    * population
    * rank
* Obtain a table with the count of crimes that occurred in all sectors in 2016, 2017 and 2018. The table must include:
    * year
    * crime
    * count
    * crime
    * cuadrante
    * sector

# STEP 1 LIST OF THE CRIME

In [1]:
#we make the function to get the data
import requests
import json
import pandas as pd
#obtain a list
def crime():
    url = f'https://hoyodecrimen.com/api/v1/crimes'
    res = requests.get(url)
    results = json.loads(res.content)
    return results

In [2]:
#we use the function
crime=crime()

In [4]:
#we read and make the table
crime = pd.read_json(json.dumps(crime['rows']), orient = 'records')
crime

                              crime
0                  HOMICIDIO DOLOSO
1        LESIONES POR ARMA DE FUEGO
2        ROBO A BORDO DE METRO C.V.
3        ROBO A BORDO DE METRO S.V.
4     ROBO A BORDO DE MICROBUS C.V.
5     ROBO A BORDO DE MICROBUS S.V.
6         ROBO A BORDO DE TAXI C.V.
7       ROBO A CASA HABITACION C.V.
8        ROBO A CUENTAHABIENTE C.V.
9               ROBO A NEGOCIO C.V.
10           ROBO A REPARTIDOR C.V.
11           ROBO A REPARTIDOR S.V.
12           ROBO A TRANSEUNTE C.V.
13           ROBO A TRANSEUNTE S.V.
14        ROBO A TRANSPORTISTA C.V.
15        ROBO A TRANSPORTISTA S.V.
16  ROBO DE VEHICULO AUTOMOTOR C.V.
17  ROBO DE VEHICULO AUTOMOTOR S.V.
18                        SECUESTRO
19                        VIOLACION

# STEP 2- ALL QUADRANTS

In [5]:
#we make the function to get these data
import requests
import json
import pandas as pd
#obtain a list
def qua():
    url = 'https://hoyodecrimen.com/api/v1/cuadrantes'
    res = requests.get(url)
    results = json.loads(res.content)
    return results
#we call the function
qua=qua()

In [6]:
#we make a table
quadrants = pd.read_json(json.dumps(qua['rows']), orient = 'records')
quadrants.head()#only print the firts 5

  cuadrante  cve_mun       municipio sector
0   P-1.1.1     9010  ALVARO OBREGON  ALPES
1  P-1.1.10     9010  ALVARO OBREGON  ALPES
2   P-1.1.2     9010  ALVARO OBREGON  ALPES
3   P-1.1.3     9010  ALVARO OBREGON  ALPES
4   P-1.1.4     9010  ALVARO OBREGON  ALPES

# STEP 3- SEARCHING CRIME WITH A COORDENATE

In [7]:
# we make a function to get the data
def coor(latitude, longitude):
    url = f'https://hoyodecrimen.com/api/v1/latlong/crimes/all/coords/{longitude}/{latitude}/distance/500'
    res = requests.get(url)
    results = json.loads(res.content)
    return results

longitude='-99.133334'
latitude='19.433735'
#we call the function and the variables.
coor=coor(latitude,longitude)

In [9]:
#we read in table
coor = pd.read_json(json.dumps(coor['rows']), orient = 'records')
coor.head()

       crime       date   hour        lat       long
0  VIOLACION 2019-08-08  20:20  19.434894 -99.131946
1  VIOLACION 2019-07-28  08:00  19.433981 -99.136270
2  VIOLACION 2019-02-18  07:30  19.433498 -99.131219
3  VIOLACION 2019-02-09  03:00  19.436161 -99.137314
4  VIOLACION 2019-01-12  21:00  19.436161 -99.137314

# STEP 4 - TOP OF CRIME OF 2016, 2017, 2018.

In [11]:
#we get the data with the function TOP.
def TOP(start_date,end_date):
    url = f'https://hoyodecrimen.com/api/v1/cuadrantes/crimes/all/top/counts?start_date={start_date}&end_date={end_date}'
    res = requests.get(url)
    results = json.loads(res.content)
    return results

#we read the first year
start_date='2016-01'
end_date='2017-12'
crimes_2016=TOP(start_date,end_date)

#we read the second year
start_date='2017-01'
end_date='2018-12'
crimes_2017=TOP(start_date,end_date)

#We read the third year
start_date='2018-01'
end_date='2018-12'
crimes_2018=TOP(start_date,end_date)
#we read and make a data frame
crimes_2016= pd.read_json(json.dumps(crimes_2016['rows']), orient = 'records')
crimes_2017= pd.read_json(json.dumps(crimes_2017['rows']), orient = 'records')
crimes_2018= pd.read_json(json.dumps(crimes_2018['rows']), orient = 'records')

#we use the function .concat to concatenate the dataframes
data=pd.concat([crimes_2016,crimes_2017,crimes_2018])

In [12]:
data.head(30)#we print the data frame

,count,crime,cuadrante,end_period,population,rank,sector,start_period
0,396,HOMICIDIO DOLOSO,(NO ESPECIFICADO),2017-12,NaN,1,NO ESPECIFICADO,2016-01
1,24,HOMICIDIO DOLOSO,P-1.2.6,2017-12,45966.0,2,PLATEROS,2016-01
2,23,HOMICIDIO DOLOSO,N-1.3.12,2017-12,17795.0,3,TICOMAN,2016-01
3,18,HOMICIDIO DOLOSO,O-2.5.7,2017-12,36811.0,4,TEZONCO,2016-01
4,17,HOMICIDIO DOLOSO,C-2.3.4,2017-12,6619.0,5,MORELOS,2016-01
5,2186,LESIONES POR ARMA DE FUEGO,(NO ESPECIFICADO),2017-12,NaN,1,NO ESPECIFICADO,2016-01
6,20,LESIONES POR ARMA DE FUEGO,O-2.1.19,2017-12,18396.0,2,OASIS,2016-01
7,19,LESIONES POR ARMA DE FUEGO,C-2.3.2,2017-12,12649.0,3,MORELOS,2016-01
8,19,LESIONES POR ARMA DE FUEGO,C-2.3.4,2017-12,6619.0,3,MORELOS,2016-01
9,17,LESIONES POR ARMA DE FUEGO,C-1.2.2,2017-12,5282.0,5,MIXCALCO-HERALDO,2016-01
10,17,LESIONES POR ARMA DE FUEGO,O-2.5.7,2017-12,36811.0,5,TEZONCO,2016-01
11,22,ROBO A BORDO DE METRO C.V.,C-2.2.14,2017-12,4567.0,1,BUENAVISTA,2016-01
12,20,ROBO A BORDO DE METRO C.V.,C-1.2.6,2017-12,2283.0,2,MIXCALCO-HERALDO,2016-01
13,15,ROBO A BORDO DE METRO C.V.,C-1.1.1,2017-12,36.0,3,REVOLUCION-ALAMEDA,2016-01
14,12,ROBO A BORDO DE METRO C.V.,C-1.1.3,2017-12,811.0,4,CORREDOR-CENTRO,2016-01
15,12,ROBO A BORDO DE METRO C.V.,N-3.2.1,2017-12,7668.0,4,PANTITLAN,2016-01
16,209,ROBO A BORDO DE METRO S.V.,C-1.2.6,2017-12,2283.0,1,MIXCALCO-HERALDO,2016-01
17,175,ROBO A BORDO DE METRO S.V.,C-2.2.14,2017-12,4567.0,2,BUENAVISTA,2016-01
18,164,ROBO A BORDO DE METRO S.V.,C-1.1.3,2017-12,811.0,3,CORREDOR-CENTRO,2016-01
19,131,ROBO A BORDO DE METRO S.V.,C-1.1.1,2017-12,36.0,4,REVOLUCION-ALAMEDA,2016-01
20,114,ROBO A BORDO DE METRO S.V.,P-3.5.9,2017-12,8447.0,5,TACUBAYA,2016-01
21,32,ROBO A BORDO DE MICROBUS C.V.,N-2.4.6,2017-12,30408.0,1,QUIROGA,2016-01
22,28,ROBO A BORDO DE MICROBUS C.V.,O-2.1.19,2017-12,18396.0,2,OASIS,2016-01
23,26,ROBO A BORDO DE MICROBUS C.V.,O-2.3.1,2017-12,32517.0,3,SANTA CRUZ,2016-01
24,25,ROBO A BORDO DE MICROBUS C.V.,O-2.1.10,2017-12,24085.0,4,OASIS,2016-01
25,21,ROBO A BORDO DE MICROBUS C.V.,(NO ESPECIFICADO),2017-12,NaN,5,NO ESPECIFICADO,2016-01
26,6,ROBO A BORDO DE MICROBUS S.V.,N-2.4.6,2017-12,30408.0,1,QUIROGA,2016-01
27,4,ROBO A BORDO DE MICROBUS S.V.,O-3.4.5,2017-12,18217.0,2,ZAPOTITLA,2016-01
28,3,ROBO A BORDO DE MICROBUS S.V.,O-2.5.7,2017-12,36811.0,3,TEZONCO,2016-01
29,3,ROBO A BORDO DE MICROBUS S.V.,O-2.5.8,2017-12,32571.0,3,TEZONCO,2016-01

# STEP 5- TABLE IN ALL SECTORS

In [13]:
#we make a function to get the data
def sectors(start_date,end_date):
    url = f'https://hoyodecrimen.com//api/v1/sectores/all/crimes/all/series?start_date={start_date}-01&end_date={end_date}-12'
    res = requests.get(url)
    results = json.loads(res.content)
    return results

In [14]:
#we run the function for 2016
start_date='2017'
end_date='2017'                                                                                                                   
data_2016=sectors(start_date, end_date)
data_2016= pd.read_json(json.dumps(data_2016['rows']), orient = 'records')
#for 2017
start_date='2017'
end_date='2017'                                                                                                                   
data_2017=sectors(start_date, end_date)
data_2017= pd.read_json(json.dumps(data_2017['rows']), orient = 'records')

#for 2018
start_date='2018'
end_date='2018'                                                                                                                   
data_2018=sectors(start_date, end_date)
data_2018= pd.read_json(json.dumps(data_2018['rows']), orient = 'records')
#we concatenate the three dataframes in one
data_table=pd.concat([data_2016,data_2017,data_2018])
#we print the new table.
data_table

,count,crime,date,population,sector
0,1,HOMICIDIO DOLOSO,2017-01-01,171082.0,ABASTO-REFORMA
1,0,HOMICIDIO DOLOSO,2017-02-01,171082.0,ABASTO-REFORMA
2,3,HOMICIDIO DOLOSO,2017-03-01,171082.0,ABASTO-REFORMA
3,3,HOMICIDIO DOLOSO,2017-04-01,171082.0,ABASTO-REFORMA
4,0,HOMICIDIO DOLOSO,2017-05-01,171082.0,ABASTO-REFORMA
5,1,HOMICIDIO DOLOSO,2017-06-01,171082.0,ABASTO-REFORMA
6,1,HOMICIDIO DOLOSO,2017-07-01,171082.0,ABASTO-REFORMA
7,3,HOMICIDIO DOLOSO,2017-08-01,171082.0,ABASTO-REFORMA
8,1,HOMICIDIO DOLOSO,2017-09-01,171082.0,ABASTO-REFORMA
9,1,HOMICIDIO DOLOSO,2017-10-01,171082.0,ABASTO-REFORMA
10,4,HOMICIDIO DOLOSO,2017-11-01,171082.0,ABASTO-REFORMA
11,1,HOMICIDIO DOLOSO,2017-12-01,171082.0,ABASTO-REFORMA
12,1,LESIONES POR ARMA DE FUEGO,2017-01-01,171082.0,ABASTO-REFORMA
13,3,LESIONES POR ARMA DE FUEGO,2017-02-01,171082.0,ABASTO-REFORMA
14,2,LESIONES POR ARMA DE FUEGO,2017-03-01,171082.0,ABASTO-REFORMA
15,1,LESIONES POR ARMA DE FUEGO,2017-04-01,171082.0,ABASTO-REFORMA
16,2,LESIONES POR ARMA DE FUEGO,2017-05-01,171082.0,ABASTO-REFORMA
17,0,LESIONES POR ARMA DE FUEGO,2017-06-01,171082.0,ABASTO-REFORMA
18,3,LESIONES POR ARMA DE FUEGO,2017-07-01,171082.0,ABASTO-REFORMA
19,1,LESIONES POR ARMA DE FUEGO,2017-08-01,171082.0,ABASTO-REFORMA
20,2,LESIONES POR ARMA DE FUEGO,2017-09-01,171082.0,ABASTO-REFORMA
21,6,LESIONES POR ARMA DE FUEGO,2017-10-01,171082.0,ABASTO-REFORMA
22,1,LESIONES POR ARMA DE FUEGO,2017-11-01,171082.0,ABASTO-REFORMA
23,3,LESIONES POR ARMA DE FUEGO,2017-12-01,171082.0,ABASTO-REFORMA
24,0,ROBO A BORDO DE METRO C.V.,2017-01-01,171082.0,ABASTO-REFORMA
25,0,ROBO A BORDO DE METRO C.V.,2017-02-01,171082.0,ABASTO-REFORMA
26,0,ROBO A BORDO DE METRO C.V.,2017-03-01,171082.0,ABASTO-REFORMA
27,0,ROBO A BORDO DE METRO C.V.,2017-04-01,171082.0,ABASTO-REFORMA
28,0,ROBO A BORDO DE METRO C.V.,2017-05-01,171082.0,ABASTO-REFORMA
29,0,ROBO A BORDO DE METRO C.V.,2017-06-01,171082.0,ABASTO-REFORMA
...,...,...,...,...,...
17416,3,ROBO DE VEHICULO AUTOMOTOR S.V.,2018-07-01,34276.0,ZARAGOZA
17417,3,ROBO DE VEHICULO AUTOMOTOR S.V.,2018-08-01,34276.0,ZARAGOZA
17418,4,ROBO DE VEHICULO AUTOMOTOR S.V.,2018-09-01,34276.0,ZARAGOZA
17419,7,ROBO DE VEHICULO AUTOMOTOR S.V.,2018-10-01,34276.0,ZARAGOZA
17420,4,ROBO DE VEHICULO AUTOMOTOR S.V.,2018-11-01,34276.0,ZARAGOZA
17421,3,ROBO DE VEHICULO AUTOMOTOR S.V.,2018-12-01,34276.0,ZARAGOZA
17422,0,SECUESTRO,2018-01-01,34276.0,ZARAGOZA
17423,0,SECUESTRO,2018-02-01,34276.0,ZARAGOZA
17424,0,SECUESTRO,2018-03-01,34276.0,ZARAGOZA
17425,0,SECUESTRO,2018-04-01,34276.0,ZARAGOZA
17426,0,SECUESTRO,2018-05-01,34276.0,ZARAGOZA
17427,0,SECUESTRO,2018-06-01,34276.0,ZARAGOZA
17428,0,SECUESTRO,2018-07-01,34276.0,ZARAGOZA
17429,0,SECUESTRO,2018-08-01,34276.0,ZARAGOZA
17430,0,SECUESTRO,2018-09-01,34276.0,ZARAGOZA
17431,0,SECUESTRO,2018-10-01,34276.0,ZARAGOZA
17432,0,SECUESTRO,2018-11-01,34276.0,ZARAGOZA
17433,0,SECUESTRO,2018-12-01,34276.0,ZARAGOZA
17434,0,VIOLACION,2018-01-01,34276.0,ZARAGOZA
17435,0,VIOLACION,2018-02-01,34276.0,ZARAGOZA
17436,0,VIOLACION,2018-03-01,34276.0,ZARAGOZA
17437,0,VIOLACION,2018-04-01,34276.0,ZARAGOZA
17438,0,VIOLACION,2018-05-01,34276.0,ZARAGOZA
17439,0,VIOLACION,2018-06-01,34276.0,ZARAGOZA
17440,0,VIOLACION,2018-07-01,34276.0,ZARAGOZA
17441,0,VIOLACION,2018-08-01,34276.0,ZARAGOZA
17442,0,VIOLACION,2018-09-01,34276.0,ZARAGOZA
17443,1,VIOLACION,2018-10-01,34276.0,ZARAGOZA
17444,2,VIOLACION,2018-11-01,34276.0,ZARAGOZA
17445,1,VIOLACION,2018-12-01,34276.0,ZARAGOZA